services:
  php:
    build: .
    container_name: poobyphp
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    container_name: poobynginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mariadb:latest
    container_name: poobymariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: courspoo
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: